[package]
name = "network_call"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid.workspace = true
serde.workspace = true
serde_json.workspace = true
ic-cdk.workspace = true

common = { path = "../common" }